esphome:
  name: esp32c5-openthread-example

zephyr:
  variant: ESP32C5

logger:
  level: VERBOSE
  #hardware_uart: UART0 # monitor via UART pins

network:
  enable_ipv6: true

openthread:
  device_type: mtd
  force_dataset: true
  tlv: !secret openthread_tlv_wed
  output_power: 0

api:

ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor_id
    type: seconds
    update_interval: 60s
  - platform: internal_temperature
    name: "Internal Temperature"
    update_interval: 60s
