esphome:
  name: esp32-wifi-example

zephyr:
  variant: ESP32

logger:

network:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: uptime
    name: "Uptime"
    update_interval: 60s
