esphome:
  name: nsim-i2c-passthrough-ex

zephyr:
  variant: NATIVESIM
  board: native_sim/native/64
  advanced:
    mac_address: "62:23:45:AF:B3:DE"

logger:
  level: VERBOSE

network:

api:

ota:
  - platform: esphome
    port: 3233
    password: !secret ota_password

i2c:
  - id: i2c_bus
    device: /dev/i2c-7
    scan: true

sensor:
  - platform: bme280_i2c
    address: 0x76
    temperature:
      name: "Temperature"
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    update_interval: 10s

debug:
  update_interval: 60s
