esphome:
  name: test-rp2350-w-mcuboot

zephyr:
  variant: rp2350
  board: rpi_pico2/rp2350a/m33/w/mcuboot
  framework:
    source:
      type: git
      ref: main
  kconfig_options:
    CONFIG_MDNS_RESPONDER_ANNOUNCE_DNS_SD: true
  advanced:
    bootloader: mcuboot

logger:
  level: DEBUG

wifi:
#  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  min_rssi: -40

api:

ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: uptime
    name: "Uptime"
    update_interval: 60s
